#!/bin/sh
pgrep -x sxhkd >/dev/null || sxhkd &
xrandr --output eDP-1-1 --mode 1920x1080
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 3

bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -r head
bspc rule -a .gscreenshot-wrapped:.gscreenshot-wrapped state=floating

xrandr --output eDP-1-1 --brightness 0.8

kitty &
